### ISSUE TITLE
References are not shown properly in UI

### ISSUE THREAD

**Issue by mohdamir** [run-llama/create-llama#57]
Have run the package from main branch and created a bot with PDF documents. There are three nodes shown as references for the answers but they are empty and not showing the part of PDF as source/reference (Screenshot attached)
<img width="1159" alt="Screenshot 2024-04-23 at 1 48 55 PM" src="https://github.com/run-llama/create-llama/assets/1610717/637aa180-6185-4593-b523-69cb45197329">

**Comment by marcusschiesser** [comment]
Thanks @mohdamir. This should only happen if you're using a Typescript backend, but not with Python. The reason is that Typescript is not adding any file metadata; I added a patch for this (https://github.com/run-llama/LlamaIndexTS/pull/758), which will be released with the next LlamaIndexTS version.

Meanwhile, if you're using a Typescript backend, I filter out source nodes without metadata, see https://github.com/run-llama/create-llama/commit/8b81b17984dfdc2099fb98af62f3bb92c55247e3

**Comment by mohdamir** [comment]
Thanks @marcusschiesser. Looking forward for the next release.

**Comment by marcusschiesser** [comment]
@mohdamir should be fixed in the latest release
